version: 2  # Dependabot 必须的版本声明
updates:    # 必须的 updates 模块
  - package-ecosystem: "npm"    # 例如：更新 npm 依赖
    directory: "/"              # 依赖文件所在目录
    schedule:
      interval: "weekly"        # 每周检查更新