name: Deploy to GitHub Pages
on: [push] # 每次 push 到 main 分支时触发
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      ALGOLIA_APP_ID: ${{ VALINE_APPID }}
      ALGOLIA_API_KEY: ${{ VALINE_APPKEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build with Hexo
        run: |
          hexo clean
          hexo generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages